# Generated by Django 4.1.4 on 2022-12-21 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=40)),
                ('fifa_ranking', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=40)),
                ('age', models.PositiveIntegerField()),
                ('player_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.country')),
            ],
        ),
    ]
